// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://selfflvzwcyblwnvqxer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbGZmbHZ6d2N5Ymx3bnZxeGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTA2MzMsImV4cCI6MjA2OTk4NjYzM30.MSeQFbUe5ISBSSogI7O_2ftVEvzbeyesCTYWa_BtcYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});